spring:
  profile:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/meelas/ms.git/
          search-paths:
            - "ConfigProperties/{application}/{profile}"
